backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "foundation"
    label: "Foundation Work"
    folder: "_posts/foundation"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "hidden", default: "foundation"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - {label: "S", value: "S"}
          - {label: "A (first)", value: "A1"}
          - {label: "A (second)", value: "A2"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "travels"
    label: "Life & Travels"
    folder: "_posts/travels"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "hidden", default: "travels"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - {label: "S", value: "S"}
          - {label: "A (first)", value: "A1"}
          - {label: "A (second)", value: "A2"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
